/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as AtendimentosRouteImport } from './routes/atendimentos'
import { Route as BackupRouteImport } from './routes/backup'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as ConveniosRouteImport } from './routes/convenios'
import { Route as DocumentosRouteImport } from './routes/documentos'
import { Route as FeriadosRouteImport } from './routes/feriados'
import { Route as FilaRouteImport } from './routes/fila'
import { Route as FinanceiroRouteImport } from './routes/financeiro'
import { Route as PacientesRouteImport } from './routes/pacientes'
import { Route as ProfissionaisRouteImport } from './routes/profissionais'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as TarefasRouteImport } from './routes/tarefas'
import { Route as UsuariosRouteImport } from './routes/usuarios'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const AtendimentosRoute = AtendimentosRouteImport.update({
  id: '/atendimentos',
  path: '/atendimentos',
  getParentRoute: () => rootRouteImport,
} as any)
const BackupRoute = BackupRouteImport.update({
  id: '/backup',
  path: '/backup',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ConveniosRoute = ConveniosRouteImport.update({
  id: '/convenios',
  path: '/convenios',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentosRoute = DocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => rootRouteImport,
} as any)
const FeriadosRoute = FeriadosRouteImport.update({
  id: '/feriados',
  path: '/feriados',
  getParentRoute: () => rootRouteImport,
} as any)
const FilaRoute = FilaRouteImport.update({
  id: '/fila',
  path: '/fila',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroRoute = FinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const PacientesRoute = PacientesRouteImport.update({
  id: '/pacientes',
  path: '/pacientes',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfissionaisRoute = ProfissionaisRouteImport.update({
  id: '/profissionais',
  path: '/profissionais',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const TarefasRoute = TarefasRouteImport.update({
  id: '/tarefas',
  path: '/tarefas',
  getParentRoute: () => rootRouteImport,
} as any)
const UsuariosRoute = UsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/atendimentos': typeof AtendimentosRoute
  '/backup': typeof BackupRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/convenios': typeof ConveniosRoute
  '/documentos': typeof DocumentosRoute
  '/feriados': typeof FeriadosRoute
  '/fila': typeof FilaRoute
  '/financeiro': typeof FinanceiroRoute
  '/pacientes': typeof PacientesRoute
  '/profissionais': typeof ProfissionaisRoute
  '/relatorios': typeof RelatoriosRoute
  '/tarefas': typeof TarefasRoute
  '/usuarios': typeof UsuariosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/atendimentos': typeof AtendimentosRoute
  '/backup': typeof BackupRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/convenios': typeof ConveniosRoute
  '/documentos': typeof DocumentosRoute
  '/feriados': typeof FeriadosRoute
  '/fila': typeof FilaRoute
  '/financeiro': typeof FinanceiroRoute
  '/pacientes': typeof PacientesRoute
  '/profissionais': typeof ProfissionaisRoute
  '/relatorios': typeof RelatoriosRoute
  '/tarefas': typeof TarefasRoute
  '/usuarios': typeof UsuariosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/atendimentos': typeof AtendimentosRoute
  '/backup': typeof BackupRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/convenios': typeof ConveniosRoute
  '/documentos': typeof DocumentosRoute
  '/feriados': typeof FeriadosRoute
  '/fila': typeof FilaRoute
  '/financeiro': typeof FinanceiroRoute
  '/pacientes': typeof PacientesRoute
  '/profissionais': typeof ProfissionaisRoute
  '/relatorios': typeof RelatoriosRoute
  '/tarefas': typeof TarefasRoute
  '/usuarios': typeof UsuariosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/atendimentos'
    | '/backup'
    | '/configuracoes'
    | '/convenios'
    | '/documentos'
    | '/feriados'
    | '/fila'
    | '/financeiro'
    | '/pacientes'
    | '/profissionais'
    | '/relatorios'
    | '/tarefas'
    | '/usuarios'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/atendimentos'
    | '/backup'
    | '/configuracoes'
    | '/convenios'
    | '/documentos'
    | '/feriados'
    | '/fila'
    | '/financeiro'
    | '/pacientes'
    | '/profissionais'
    | '/relatorios'
    | '/tarefas'
    | '/usuarios'
  id:
    | '__root__'
    | '/'
    | '/agenda'
    | '/atendimentos'
    | '/backup'
    | '/configuracoes'
    | '/convenios'
    | '/documentos'
    | '/feriados'
    | '/fila'
    | '/financeiro'
    | '/pacientes'
    | '/profissionais'
    | '/relatorios'
    | '/tarefas'
    | '/usuarios'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendaRoute: typeof AgendaRoute
  AtendimentosRoute: typeof AtendimentosRoute
  BackupRoute: typeof BackupRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  ConveniosRoute: typeof ConveniosRoute
  DocumentosRoute: typeof DocumentosRoute
  FeriadosRoute: typeof FeriadosRoute
  FilaRoute: typeof FilaRoute
  FinanceiroRoute: typeof FinanceiroRoute
  PacientesRoute: typeof PacientesRoute
  ProfissionaisRoute: typeof ProfissionaisRoute
  RelatoriosRoute: typeof RelatoriosRoute
  TarefasRoute: typeof TarefasRoute
  UsuariosRoute: typeof UsuariosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atendimentos': {
      id: '/atendimentos'
      path: '/atendimentos'
      fullPath: '/atendimentos'
      preLoaderRoute: typeof AtendimentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backup': {
      id: '/backup'
      path: '/backup'
      fullPath: '/backup'
      preLoaderRoute: typeof BackupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/convenios': {
      id: '/convenios'
      path: '/convenios'
      fullPath: '/convenios'
      preLoaderRoute: typeof ConveniosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentos': {
      id: '/documentos'
      path: '/documentos'
      fullPath: '/documentos'
      preLoaderRoute: typeof DocumentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feriados': {
      id: '/feriados'
      path: '/feriados'
      fullPath: '/feriados'
      preLoaderRoute: typeof FeriadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fila': {
      id: '/fila'
      path: '/fila'
      fullPath: '/fila'
      preLoaderRoute: typeof FilaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro': {
      id: '/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof FinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pacientes': {
      id: '/pacientes'
      path: '/pacientes'
      fullPath: '/pacientes'
      preLoaderRoute: typeof PacientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profissionais': {
      id: '/profissionais'
      path: '/profissionais'
      fullPath: '/profissionais'
      preLoaderRoute: typeof ProfissionaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tarefas': {
      id: '/tarefas'
      path: '/tarefas'
      fullPath: '/tarefas'
      preLoaderRoute: typeof TarefasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usuarios': {
      id: '/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof UsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRoute: AgendaRoute,
  AtendimentosRoute: AtendimentosRoute,
  BackupRoute: BackupRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  ConveniosRoute: ConveniosRoute,
  DocumentosRoute: DocumentosRoute,
  FeriadosRoute: FeriadosRoute,
  FilaRoute: FilaRoute,
  FinanceiroRoute: FinanceiroRoute,
  PacientesRoute: PacientesRoute,
  ProfissionaisRoute: ProfissionaisRoute,
  RelatoriosRoute: RelatoriosRoute,
  TarefasRoute: TarefasRoute,
  UsuariosRoute: UsuariosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
